<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Loginmember extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        
        $this->load->model('Model_member');
        $this->load->model('Model_distributor');
    }

    public function index()
    {
		if($this->session->userdata('logined') && $this->session->userdata('logined') == true)
		{
			redirect('Home_Member/index');
		}

		#Cek session Distributor
		else if ($this->session->userdata('logined_dis') && $this->session->userdata('logined_dis') == true) {
			redirect('Home_Distributor/index');
		}
		
		if(!$this->input->post())
		{
			$this->load->view('Member/LoginMember');
		}


		else
		{
			$ceklogin = $this->Model_member->ceklogin
			(	$this->input->post('username'),
				$this->input->post('password')
			);

			if(!empty($ceklogin))
			{
				$this->session->set_userdata('username', $ceklogin->username);
				$this->session->set_userdata('logined', true);
				
				redirect("Home_Member/index");
			}
			
			else if(!$ceklogin)#cek login distributor
			{
				$ceklogin_distributor = $this->Model_distributor->ceklogin_distributor
				(
					$this->input->post('username'),
					$this->input->post('password')
				);
				if(!empty($ceklogin_distributor)){
					$this->session->set_userdata('username', $ceklogin_distributor->username_dis);
					$this->session->set_userdata('logined_dis', true);
					redirect("Home_Distributor/index");
				}
			}
			else 
			{
				redirect("/");
			}
		}
        
    } 
	
	public function logout()
    {
		$this->session->unset_userdata('logined');
		redirect("/");
    } 

    public function logout_dis()
    {
    	$this->session->unset_userdata('logined_dis');
    	redirect("/");
    }
}

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */