<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class LoginAdmin extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Model_admin');
        
    }

    public function index()
    {
		if($this->session->userdata('loginadmin') && $this->session->userdata('loginadmin') == true)
		{
			redirect('Admin_Controller/tampil_chart');
		}
		
		if(!$this->input->post())
		{
			$this->load->view('Admin/Loginadmin');
		}
		else
		{
			$ceklogin = $this->Model_admin->ceklogin
			(	$this->input->post('username_admin'),
				$this->input->post('password_admin')
			);

			if(!empty($ceklogin))
			{
				$this->session->set_userdata('username_admin', $ceklogin->username);
				$this->session->set_userdata('loginadmin', true);
				
				redirect("Admin_Controller/tampil_chart");
			}
			else 
			{
				redirect("LoginAdmin/index");
			}
		}
        
    } 
	
	public function logout()
    {
		$this->session->unset_userdata('loginadmin');
		redirect("LoginAdmin/index");
    } 
}

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */